travis:
  secure:
    BINSTAR_TOKEN: RGtq1PWSAlT6DxNwkt7dj22wCMhr3YecnuLmSRFB60nQCO+GAwR4wvlvjdn5o9KmAxksNtu+6gmutztKUESiHfxmhUUu1yJuM2qEow9R0ZPwp7cPkUc8m2P8nMF1wnSOKnsi46g8r2Mzc2v1avVxT/NJsNd+ueJnqYjCLl2jiRT++3DHSM6xwvGM7HBeQY2Tj2aWAwfCKVw+THaF19WKKxYuONC9tfWYm1xOqZu/U68HvD8zXqNMOVDAHHRwq0Pr/aSJIBsAqVcc69FnJhR3FkE/XmGJVv4CyWjyu5e5IGQfq3o8ZcTP/TgT9eXWdQ0vT7ID+iGXcCmao2BIR5wbyRUF+sKbG5hkHqD9eo7bpJu6N2S4ngbmvro3wpFQaVCFtO5I6D8ckUGPgLEMM51Z8Dielpn7djoPXfgUd2Z2xF4RjZg20CkbqjZM6L6o8G/W9UbeP/7PlQCiLLhbyEu1VoX8/jRPgPS5jyBjisAyjy9dyEbhf4iHwDhpRFy/MpbXOyOlYr4/3thOlyD+nMMSADyALhtqtaFE7RJfI+XwO71+D1OqwIm/SX8EemRGBK/JWo36zoDHgTKsGdj8FoE/1h7XBUJa/1sH4HxxPG0sUNBxGbSG44qVLyimc0637a4NJgBVKmI5+iKtqfStgdl663lZz7A4C1nUQPd1KWpXTy4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
